name: Experiment
on: 
  workflow_dispatch:

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: main }
    - name: call api
      run: ./github-action-script.sh

  job2:
    name: Debug2
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: main }
    - name: call api
      run: chmod +x ./slot20.sh
      
