name: Experiment
on: 
  schedule:
  - cron: '55,56,57,58,59,0 5,6 * * *'
  workflow_dispatch:

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: main }
    - name: List files
      run: ./github-action-script.sh
