name: main
on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Permission File run
        run: ./github-action-script.sh 
